### ISSUE TITLE
Not working on Ubuntu 15.04

### ISSUE THREAD

**Issue by varlesh** [Serranya/deadbeef-mpris2-plugin#10]
DeaDBeeF 0.6.2
deadbeef-mpris2-plugin 1.8
LOG:
GLib-GIO:ERROR:/build/buildd/glib2.0-2.44.1/./gio/gdbusconnection.c:4188:invoke_get_property_in_idle_cb: assertion failed: (error != NULL)

**Comment by Serranya** [comment]
i guess the issue occures when you try to send some message to DeaDBeef with your mpris client.

What MPRIS client are you using in which version?
Please run dbus-monitor while interacting with DeaDBeeF and send me that log.

I guess somewhere in my code im not sending an answer to an request but also not throwing an error. And thats not allowed.

**Comment by varlesh** [comment]
MPRIS used for volume indicator and kdeconnect
LOG dbus-monitor:
http://pastebin.com/aV1inVHZ
