### ISSUE TITLE
can't make in LM 17.3

### ISSUE THREAD

**Issue by thob** [Serranya/deadbeef-mpris2-plugin#13]
`./configure` works but created a few errors like 

`configure: error: in `/home/nnn/Downloads/deadbeef-1.8':`
  
`configure: error: C compiler cannot create executables`

once I hit make I get  
 `Error "make: *** No rule to make target `install'. Stop."`

Any idea?

**Comment by Serranya** [comment]
Can you post the entire output of ``./configure``.
Also post the contents of config.log. It should get created by ``./configure``

**Comment by thob** [comment]
Here we go
>
checking for a BSD-compatible install... /usr/bin/install -c  
checking whether build environment is sane... yes  
checking for a thread-safe mkdir -p... /bin/mkdir -p  
checking for gawk... gawk  
checking whether make sets $(MAKE)... yes  
checking whether make supports nested variables... yes  
checking whether make supports nested variables... (cached) yes  
checking for gcc... gcc  
checking whether the C compiler works... no  
configure: error: in `/home/thomas/Downloads/deadbeef-1.8':  
configure: error: C compiler cannot create executables  
See `config.log' for more details  


[config.log.zip](https://github.com/Serranya/deadbeef-mpris2-plugin/files/72687/config.log.zip)

**Comment by Serranya** [comment]
Do you have the ``build-essential`` package installed ? I think you are missing the -dev version of libc

**Comment by thob** [comment]
we're getting closer I believen. I installed it. Run ./configure Now I get 

>
configure: error: glibc-2 is required for this package

**Comment by Serranya** [comment]
You are missing the ``-dev`` package again. Please install ``libglib2.0-dev`` :)

**Comment by thob** [comment]
oh. thanks.installed. Now I get  this for  `make install`:
>
CC       src/mpris_la-mpris.lo
In file included from src/mpris.c:3:0:
src/mprisServer.h:8:31: fatal error: deadbeef/deadbeef.h: Datei oder Verzeichnis nicht gefunden
#include <deadbeef/deadbeef.h>
                               ^
compilation terminated.
make: *** [src/mpris_la-mpris.lo] Fehler 1

**Comment by Serranya** [comment]
You probably installed DeaDBeeF from the .deb from the DeaDBeeF website. In that case DeaDBeeF is not where im searching for it. Try my second answer from https://github.com/Serranya/deadbeef-mpris2-plugin/issues/9

**Comment by thob** [comment]
thanks. I'll check
