### ISSUE TITLE
Compat fixes

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [Serranya/deadbeef-mpris2-plugin#14]
These are the changes I had to make to build this plugin on "deadbeef plugin builder", with GLIB 2.28 and friends, and older autotools.

https://github.com/Alexey-Yakovenko/deadbeef-plugin-builder/blob/master/plugins/mpris/make.diff

You don't have to merge these, but they make stuff compatible with more systems.

**Comment by Alexey-Yakovenko** [comment]
Would also be nice if you can test if the build here works correctly, after the g_thread changes: http://deadbeef.sourceforge.net/plugins.html

**Comment by Serranya** [comment]
I will test your 64bit build.

Regarding your patch: Is it required to put all the dependencies in one check ?

If not I would like to keep it the way it was to provide better error messages in case some dependency is missing.

The remaining rules should be fine but i need to test them first

**Comment by Serranya** [comment]
Also instead of just replacing g_thread_new / unref and join I will use an ifdef.

**Comment by Alexey-Yakovenko** [comment]
yeah, putting dependencies in one check is necessary in the plugin builder.. because they are set externally in the manifest like this: 

```
 ENV: {
            MPRIS_DEPS_CFLAGS: "$GTK300_CFLAGS",
            MPRIS_DEPS_LIBS: "$GTK300_LIBS",
        },
```

As I mentioned, it is not necessary to change anything on your side. Only if you find anything useful

**Comment by Serranya** [comment]
So i came finally around to test your build. It works fine on x64 with glibc 2.23. Not even an deprecation warning.

**Comment by Serranya** [comment]
After my updates you should be able to simplify your patch. Thank you for your notification :)

**Comment by Alexey-Yakovenko** [comment]
> with glibc 2.23

I guess, you meant GLIB, not GLIBC

**Comment by Serranya** [comment]
haha you are right. I never knew they are different
