### ISSUE TITLE
Fails to start on Arch

### ISSUE THREAD

**Issue by Xylemon** [Serranya/deadbeef-mpris2-plugin#16]
I'm on Arch Linux 64-bit with glib2 2.48 and DeaDBeeF 0.7.2 installed, and DeaDBeeF fails to start with this plugin (latest version, 1.9) installed. DeaDBeeF spits out the following in terminal:

```
(deadbeef:9117): GLib-GObject-WARNING **: cannot register existing type 'GtkBuildable'

(deadbeef:9117): GLib-GObject-CRITICAL **: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed

(deadbeef:9117): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(deadbeef:9117): GLib-GObject-WARNING **: cannot register existing type 'GtkWidget'

(deadbeef:9117): GLib-GObject-WARNING **: cannot add class private field to invalid type '<invalid>'

(deadbeef:9117): GLib-GObject-WARNING **: cannot add private field to invalid (non-instantiatable) type '<invalid>'
```

I used the following PKGBUILD to build and install the plugin: https://aur.archlinux.org/packages/deadbeef-mpris2-plugin/

**Comment by Serranya** [comment]
I am using Arch myself, and its working fine for me.

Can you uninstall the plugin and confirm that deadbeef is now working again? Just to make sure my plugin is really causing this.

**Comment by Xylemon** [comment]
@Serranya, I have tested it with just the plugin before, and it DeaDBeeF still failed to run. As always, whether it's with multiple plugins, or just this one, it fails to start. Since you're using Arch as well and reporting no problems, is there perhaps a dependency I'm missing?

**Comment by Serranya** [comment]
Im pretty sure the PKGBUILD is listing all reqired dependencies (Its my own PKGBUILD). I have no idea where this comes from...

Im leaving tomorrow morning for hollidays. So I wont be able to look into this problem for the rest of the Month.

But you are the only User with that problem. I fear something else in your setup is causing these problems.

**Comment by Serranya** [comment]
Please also try building the plugin with the ``--enable-debug`` flag.

**Comment by Xylemon** [comment]
As I thought, you were right. It seems this bug is coming from loading the "gtk3-nocsd" library. It's very odd considering I only use GTK2 plugins for DeaDBeeF, it's affecting only the mpris2 plugin, but I'll have to report this to the gtk3-nocsd developers. Thanks for looking into this anyway.
