### ISSUE TITLE
Seek doesn't work

### ISSUE THREAD

**Issue by kosivantsov** [Serranya/deadbeef-mpris2-plugin#17]
running command
`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.DeaDBeeF /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Seek int64:5000000` (or -5000000) 
makes deadbeef jump to next file instead of seeking forward (or backward).
The same command with another player specified (VLC, for instance, among others) behaves as expected.

**Comment by Serranya** [comment]
I guess you seek past the current track. Do you know if this is the case?

In the case of the forward seek this is the behaviour [MPRIS2 specifies](https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Method:Seek). But the backward seek should just reset the current file to position 0 and not play the previous file.

What behaviour do you expect?

I will look into this.

**Comment by kosivantsov** [comment]
>I guess you seek past the current track. Do you know if this is the case?

I know it's not the case, as the observed behaviour doesn't depend on the int64 value I submit. Even if I try to fast forward just one second, the player jumps to the next track. If I submit a negative value to rewind, it still jumps to the **next** track.

In other MPRIS2-compatible players the above mentioned command (with the appropriate instance name, not DeaDBeeF, of course) skips forward (positive value) and backward (negative value) by 5 seconds within the current track. This is exactly what is expected according to the linked [MPRIS2 specifications](https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Method:Seek).

> But the backward seek should just reset the current file to position 0 and not play the previous file.

Reset should occur only if the negative offset is greater than the current position. Otherwise it should skip back in the current track by the identified offset, and not jump to the previous file, of course. But, as mentioned in the first post and here, jumping to the **previous** track actually never occurs, it's **always** the **next** track regardless the actual value or its positivity/negativity.

**Comment by kosivantsov** [comment]
It looks like the problem is here:
`			if (newPositionInMilliseconds > durationInMilliseconds) {
				deadbeef->sendmessage(DB_EV_NEXT, 0, 0, 0);
			}` (lines 372-374 in `mprisServer.c`).
Seems like the result of the `newPositionInMilliseconds` calculation somehow is always greater than `durationInMilliseconds`, and therefore always jumps to the next track.

**Comment by Serranya** [comment]
I could reproduce the issue.

**Comment by Serranya** [comment]
The issue should be fixed on master. Can you test the current development version? I will release a fixed version after you can confirm that the bug is gone.

**Comment by kosivantsov** [comment]
I confirm that the bug is fixed now. Thank you very much for looking into it. The issue can be closed.
