### ISSUE TITLE
Metadata not properly showing on Gnome Media Player Extension

### ISSUE THREAD

**Issue by amartin1911** [Serranya/deadbeef-mpris2-plugin#26]
I was about to post this issue on extension's [page](https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer) but I've tested the extension against other players (Rhytmbox, Clementine, VLC) and it's working nicely. So, I assumed that mpris2 needs an update.

I've installed the mpris plugin straight from source (not the tarball), and the gnome media player extension straight from the official Gnome extensions site. However, when I open DeadBeef this is what's being shown (no metadata) [[PIC HERE]](https://drive.google.com/open?id=0B84aipcjuTNoYmt5Z0I3ZGxueW8)

However, if I lock my session, and re-login, the metadata appears! But it's static, it doesn't get updated at all (Current song is not Warriors). [[PIC HERE]](https://drive.google.com/open?id=0B84aipcjuTNoSUVqSzZnajA3NW8)

I don't know if it's a problem with your extension, gnome media player's or my OS. Please, any help would be appreciated.

I'm using Ubuntu Gnome 16.04.02, with Gnome 3.18.5.

**Comment by saivert** [comment]
This is a bug with that specific Gnome shell extension. They seem to be slow to post updates to Gnome extensions website. 
Try a more recent release direct from their github (https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/releases).

**Comment by amartin1911** [comment]
You were absolutely right. They've just have pushed an update to their website, and everything works fine now. 

Thanks!
