### ISSUE TITLE
Need LICENSE file

### ISSUE THREAD

**Issue by Vascom** [Serranya/deadbeef-mpris2-plugin#32]
Please add LICENSE file contiining text of license for deadbeef-mpris2-plugin code.

**Comment by Serranya** [comment]
Closed in bf93eb31ed9b112a0129b08a7ba987ad0b0cc4b8.

**Comment by Vascom** [comment]
Thanks.

**Comment by Vascom** [comment]
Please add this file in release tar.gz archive.

**Comment by Serranya** [comment]
The file will now be included in the distribution onward from the next release.
