### ISSUE TITLE
The progress bar doesn't move in KDE connect

### ISSUE THREAD

**Issue by laichiaheng** [Serranya/deadbeef-mpris2-plugin#35]
I've tried audacious, it doesn't have the problem, but it happens to deadbeef-mpris2-plugin, please help.

**Comment by laichiaheng** [comment]
By the way, I install it via the AUR.

**Comment by Serranya** [comment]
Why did you report the aur package outdated? 1.10 is the most recent release.

**Comment by saivert** [comment]
I just installed KDE Connect and set it up just for this. I cannot reproduce it.
Progress bar is certainly moving along here.

**Comment by laichiaheng** [comment]
@saivert which version of the mpris2 plugin are you using?

**Comment by laichiaheng** [comment]
It has been solved by installing the git version of deadbeef-mpris2-plugin.
