### ISSUE TITLE
aclocal: warning: couldn't open directory 'm4': No such file or directory

### ISSUE THREAD

**Issue by laichiaheng** [Serranya/deadbeef-mpris2-plugin#36]
It happens when I try to `autoreconf --install`

**Comment by Serranya** [comment]
This is a known warning and the build should complete successfull.

**Comment by laichiaheng** [comment]
@Serranya It doesn't work, here is the message when I do `sudo make install`
```
make[1]: Entering directory '/home/user/deadbeef-mpris2-plugin'
 /usr/bin/mkdir -p '/usr/local/lib/deadbeef'
 /bin/sh ./libtool   --mode=install /usr/bin/install -c   mpris.la '/usr/local/lib/deadbeef'
libtool: install: /usr/bin/install -c .libs/mpris.so /usr/local/lib/deadbeef/mpris.so
libtool: install: /usr/bin/install -c .libs/mpris.lai /usr/local/lib/deadbeef/mpris.la
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/sbin" ldconfig -n /usr/local/lib/deadbeef
----------------------------------------------------------------------
Libraries have been installed in:
   /usr/local/lib/deadbeef

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
make[1]: Nothing to be done for 'install-data-am'.
make[1]: Leaving directory '/home/user/deadbeef-mpris2-plugin'
```

**Comment by Serranya** [comment]
This message informs you that the plugin has been successfully installed into `/usr/local/lib/deadbeef`.

What do you mean by 

>  It doesn't work

Is there no mpris.la file in `/usr/local/lib/deadbeef` after make install?

If DeadBeef is not picking up the plugin the reason could be that it is installed into a different directory than /usr/local/lib/deadbeef.

**Comment by laichiaheng** [comment]
You're right, there is nothing in /usr/local/lib/deadbeef, but they are in /usr/lib/deadbeef.
How to change the directory?

**Comment by laichiaheng** [comment]
It works after I do it `sudo mv mpris.{la,so} /usr/lib/deadbeef/`
It has no issue with this problem: #35 
Maybe there is a need for release new stable version of deadbeef-mpris2-plugin?

**Comment by Serranya** [comment]
@laichiaheng try running configure like this `/configure --prefix /usr`. The .la should then be placed in the correct directory when installing.

**Comment by Serranya** [comment]
What I forgott to mention... you only really need the .so file. Not the .la file
