### ISSUE TITLE
client seek bar is not updated after seek occured via mpris

### ISSUE THREAD

**Issue by Meru** [Serranya/deadbeef-mpris2-plugin#43]
Take a look at this progress-bar: https://i.imgur.com/m4QjyMe.png
While it works perfectly, if you want to change the position inside of the playing track, it may take up to 8 seconds for the progress bar to refresh its state after a mouse click was performed on a different position. Before the update happens it gets reset to the beginning of the track and keeps "ticking" each second (without affecting the actual playback).
Is there a way to improve that somehow? It feels that mpris plugin should report current playback state more often than it currently does or perhaps if an action is detected - immediately trigger some kind of "refresh".

Edit: just tested. if for example we will look at the progressbar at 50% and change playing position in the player, it takes about the same time for it to update. So mpris definitely should update more often. I would say make it at least within 3 seconds... if there are some performance concerns. But ideally - every second.

**Comment by Serranya** [comment]
@Meru 
the plugin does not broadcast it currents position in the Track. Instead the client has to read that property to know the current position.

What the plugin does it that it broadcasts a notification when the user seeks in the track manually. E.g with the progress bar in deadbeef.

It does not howerver emit the seek notification if the seek is triggered via MPRIS. The reason being that the client should know that a seek occured since it's the one who likely initiated the seek in the first place.

I think it was that way in the past but we changed it for some reason.

But I aggree with you that something about the behaviour is odd.

**Comment by Serranya** [comment]
https://github.com/Serranya/deadbeef-mpris2-plugin/commit/be951df2fb75dcef7b2f46b9382941e7e29824b6 is the commit that changed the behaviour

**Comment by Serranya** [comment]
@saivert ping

**Comment by kuba160** [comment]
I am using KDE and seeking through mpris tray control works as intended.

**Comment by Meru** [comment]
@Serranya from that commit:
> I have checked the implementations in Rhythmbox, Audacious and lollypop and none of them emit seeked in response to Seek and SetPosition.
I'm sure the same seekbar responds instantly in case of Rhythmbox

**Comment by Meru** [comment]
Also, due to title change I want to clarify. If seek occurs in deadbeef - it is not updated as well.

**Comment by Serranya** [comment]
> If seek occurs in deadbeef - it is not updated as well.

Oh that's interesting.  Especially since rythmbox seems to be working. I will have to take a closer look.

**Comment by Meru** [comment]
To be precise, in both cases it IS updated, but gets set to 0 and it takes 8sec to "recover". So maybe it just being set wrong?

**Comment by saivert** [comment]
I see you are using Linux Mint and the MPRIS client in Cinnamon. I have installed Linux Mint now and I can reproduce the issue. I will be looking into it today.

**Comment by saivert** [comment]
@Meru can you try the latest code now?

**Comment by Meru** [comment]
@saivert
Latest codebase works for me. Seekbar responds instantly now. Thanks!
