### ISSUE TITLE
Status Returns only Stop

### ISSUE THREAD

**Issue by TheBabu** [Serranya/deadbeef-mpris2-plugin#46]
Whenever I use Deadbeef, the `playerctl status` output always prints "Stopped" even when the music is playing.
But `playerctl metadata` seems to be working fine.

**Comment by saivert** [comment]
What version of this plugin are you using? I cannot reproduce this using playerctl 2.0 and deadbeef-mpris2-plugin
 v.1.13

**Comment by TheBabu** [comment]
I reinstalled the plugin it is sayings its version `1.13-1`, I don't think I have any other MPRIS servers. How would I exactly check such a factor?

**Comment by TheBabu** [comment]
Wait for some sort of reason reinstalling seemed to fix it by itself...
False Alarm, closing issue
