### ISSUE TITLE
[Fedora] "configure: error: glibc-2 is required for this package"

### ISSUE THREAD

**Issue by blackICE19240** [Serranya/deadbeef-mpris2-plugin#48]
```
checking for GLIB_DEPS... no
configure: error: glibc-2 is required for this package
```

```
Package glibc-2.32-6.fc33.x86_64 is already installed.
Package glibc-2.32-6.fc33.i686 is already installed.
```

It seems as if it doesn't like the fedora version of glibc but with that said I'm stupid so please forgive me if I have completely the wrong idea :)

**Comment by Serranya** [comment]
Im not entirely sure but I think you need the `glibc-devel` package on fedore if you want to compile code against glibc.

**Comment by Serranya** [comment]
@blackICE19240 Did my comment help you resolve the issue or were you able to solve it on your own? I would like to close the issue unless there is still a problem.

**Comment by blackICE19240** [comment]
Sorry, I thought I had already replied. I already had `glibc-devel-2.32-6.fc33.x86_64` installed so i installed the i686 version too but unfortunately I still got the same error. Any other ideas?

**Comment by Serranya** [comment]
No sorry, I have no idea whats going wrong here.

**Comment by blackICE19240** [comment]
Well thanks anyway, I'll let you know if i find a solution. In the mean time, if anyone else using fedora does or doesn't have this problem, please let me know.

**Comment by vandergail** [comment]
@blackICE19240 not that it solves this issue but there is a build of this plugin in the RPMFusion-free repository.

**Comment by blackICE19240** [comment]
@vandergail Thank you, I'm not sure how I failed to notice that as it's my usual way of installing things. It solved my problem but I'm not sure if I should close this since it doesn't really solve _this_ problem. @Serranya It's up to you :)

**Comment by saivert** [comment]
That is because they package you actually want is named `glib2-devel`.

**Comment by Serranya** [comment]
Im closing this as this plugin is no longer maintained here. Please use https://github.com/DeaDBeeF-Player/deadbeef-mpris2-plugin instead.
