### ISSUE TITLE
Comment given as artist name

### ISSUE THREAD

**Issue by greatquux** [Serranya/deadbeef-mpris2-plugin#6]
![image](https://cloud.githubusercontent.com/assets/1655942/5667777/71a887a8-9738-11e4-8f55-8d8cf57268ac.png)

It appears that the artist name is not shown but rather the comment is shown instead.

**Comment by greatquux** [comment]
BTW - thanks so much for forking and starting this up again! :)

**Comment by Serranya** [comment]
Found the bug and killed it.
I will release a new version which will include this fix.

Thank you for contributing :)
