### ISSUE TITLE
Crash when there's no default_cover

### ISSUE THREAD

**Issue by cboxdoerfer** [Serranya/deadbeef-mpris2-plugin#7]
The plugin segfaults in strlen because apparently get_default_cover() returns NULL. That's the line:
https://github.com/Serranya/deadbeef-mpris2-plugin/blob/master/src/mprisServer.c#L162

Backtrace:
http://pastebin.com/raw.php?i=WgqKeAdA

And btw. thx for the plugin :)

**Comment by Serranya** [comment]
Hmm I cannot reproduce the issue on my system. On what system are you running, and which version of DeaDBeeF are you using ?

I will add a null check anyways.

Thank you for contributing :)

**Comment by cboxdoerfer** [comment]
System is Arch Linux and DeaDBeeF is build from trunk. I will test the fix and report if the issue remains or not. :)

**Comment by Serranya** [comment]
Should be fixed in 59a45a27048bf4222cea1bdb960794b7226ae7d2

**Comment by cboxdoerfer** [comment]
Yep, works fine. Thx :)
