### ISSUE TITLE
segfault on some files (deadbeef-git)

### ISSUE THREAD

**Issue by Soukyuu** [Serranya/deadbeef-mpris2-plugin#8]
Recently stumbled upon this plugin, thanks for implementing.
I'm using archlinux x64 and have installed deadbeef-git from AUR, as well as deadbeef-mpris2-plugin.

I'm getting the following crash on some files:
```
MPRIS Debug Info: get Metadata duration: 288000000
MPRIS Debug Info: get Metadata album: Complication
MPRIS Debug Info: get Metadata albumArtist: (null)
MPRIS Debug Info: get Metadata artist: ROOKiEZ is PUNK’D
MPRIS Debug Info: getting cover for album Complication
MPRIS Debug Info: cover for Complication not ready. Using default artwork
Segmentation Fault
backtrace() returned 10 addresses
deadbeef() [0x403aa1]
/usr/lib/libc.so.6(+0x33540) [0x7fe0e965f540]
/usr/lib/libc.so.6(strlen+0x2a) [0x7fe0e96ac20a]
/usr/lib/deadbeef/mpris.so(getMetadataForTrack+0x7d0) [0x7fe0cf421f30]
/usr/lib/deadbeef/mpris.so(emitMetadataChanged+0x38) [0x7fe0cf422a98]
/usr/lib/deadbeef/mpris.so(+0x1cd7) [0x7fe0cf420cd7]
deadbeef() [0x404b1f]
deadbeef() [0x404e29]
/usr/lib/libpthread.so.0(+0x7374) [0x7fe0e99d6374]
/usr/lib/libc.so.6(clone+0x6d) [0x7fe0e971427d]
```
Removing the plugin makes the file play fine again.

**Comment by Serranya** [comment]
Can you test the latest git version of this plugin ?

    git clone git@github.com:Serranya/deadbeef-mpris2-plugin.git
    cd deadbeef-mpris-2-plugin
    autoreconf --install
    configure --prefix=/usr
    make
    sudo make install

**Comment by Soukyuu** [comment]
Latest git seems to be working fine so far (the song that used to crash it now doesn't)

**Comment by Serranya** [comment]
Ok. I will release a new version of this plugin today to fix this issue

**Comment by Serranya** [comment]
The new version is [released](https://github.com/Serranya/deadbeef-mpris2-plugin/releases/tag/v1.8).

**Comment by Soukyuu** [comment]
Thank you!
