### ISSUE TITLE
Can't build the plugin, can't find deadbeef.h

### ISSUE THREAD

**Issue by VivienV** [Serranya/deadbeef-mpris2-plugin#9]
I tried following the instructions but I get the following error:
```
  CC       src/mpris_la-mpris.lo
In file included from src/mpris.c:3:0:
src/mprisServer.h:8:31: fatal error: deadbeef/deadbeef.h: No such file or directory
 #include <deadbeef/deadbeef.h>
                               ^
compilation terminated.
make: *** [src/mpris_la-mpris.lo] Error 1
```

I'm on Ubuntu 14.04, deadbeef installed via the deb package in the official website.

**Comment by Serranya** [comment]
Hmm yes this will not work since DeaDBeeF is not installed in the standard location.

Can you try to build the plugin like this:

    ./configure --prefix=/opt/deadbeef
    make
    sudo make install

**Comment by VivienV** [comment]
Still no luck, same error message :(

(Not sure if this is relevant, but I did check and deadbeef.h is indeed in /opt:
/opt/deadbeef/include/deadbeef/deadbeef.h)

**Comment by Serranya** [comment]
I will try to reproduce the issue in an ubuntu vm.

**Comment by Serranya** [comment]
Can you try the following:

    env CPPFLAGS ="$CPPFLAGS -I/opt/deadbeef/include/" ./configure --prefix=/opt/deadbeef
    make
    sudo make install

**Comment by VivienV** [comment]
Thanks, it works now!
